// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Submission struct {
	ID                int32     `json:"id"`
	FromUserID        int32     `json:"from_user_id"`
	ToTaskID          int32     `json:"to_task_id"`
	TaskSubtasks      int32     `json:"task_subtasks"`
	SubmissionAnswers []string  `json:"submission_answers"`
	CreatedAt         time.Time `json:"created_at"`
}

type Task struct {
	ID          int32  `json:"id"`
	Shortname   string `json:"shortname"`
	Problemname string `json:"problemname"`
	Content     string `json:"content"`
	// max 6 min 1
	Subtasks  int32     `json:"subtasks"`
	Answers   []string  `json:"answers"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID              int32     `json:"id"`
	Username        string    `json:"username"`
	Fullname        string    `json:"fullname"`
	PasswordEncoded string    `json:"password_encoded"`
	Usertype        int32     `json:"usertype"`
	CreatedAt       time.Time `json:"created_at"`
}
